'use strict';
const allLinks = [...document.querySelectorAll('.sidebar a')];
function markSelected(link) { allLinks.forEach(item => {item.classList.toggle('active',item===link);if(item===link)item.setAttribute('aria-current','page');else item.removeAttribute('aria-current');}); }
allLinks.forEach(link => link.addEventListener('click',()=>markSelected(link)));
const initial = sidebarEntries.find(entry=>entry.name==='Device Pitch');
if(initial){currentTemplate=initial.template;renderTemplate(initial.template);markSelected(allLinks.find(link=>link.textContent===initial.name));}
pitchForm.addEventListener('submit',event=>event.preventDefault());
// Preserve all the existing templates and actions while making guided fields accessible.
const branchObserver=new MutationObserver(()=>{document.querySelectorAll('#branch-node-fields label').forEach(label=>{const input=label.nextElementSibling;if(input?.id)label.htmlFor=input.id;});});
branchObserver.observe(document.getElementById('branch-content'),{childList:true,subtree:true});
document.querySelectorAll('.modal').forEach(modal=>{modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');let returnFocus=null;const observer=new MutationObserver(()=>{if(modal.style.display!=='none'){returnFocus=document.activeElement;modal.querySelector('input,textarea,button')?.focus();}else{returnFocus?.focus?.();}});observer.observe(modal,{attributes:true,attributeFilter:['style']});modal.addEventListener('keydown',event=>{if(event.key==='Escape'){modal.querySelector('.close-btn')?.click();}if(event.key==='Tab'){const focusable=[...modal.querySelectorAll('button,input,select,textarea,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_pitch',title:'Configure pitch',description:'Open a standard pitch template and fill its fields. Returns the preview; does not copy or send.',inputSchema:{type:'object',properties:{name:{type:'string'},fields:{type:'object',additionalProperties:{type:'string'}}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.name!=='string'||(input.fields!=null&&(typeof input.fields!=='object'||Array.isArray(input.fields))))throw new Error('Provide a template name and field values.');const t=templates.find(t=>t.name===input.name);if(!t)throw new Error('Unknown pitch template.');for(const [id,value] of Object.entries(input.fields||{})){const field=t.fields.find(f=>f.id===id);if(!field||typeof value!=='string'||(field.options&&!field.options.includes(value)))throw new Error('Invalid field: '+id);}currentTemplate=t;renderTemplate(t);for(const [id,value]of Object.entries(input.fields||{}))document.getElementById(id).value=value;updatePreview();markSelected(allLinks.find(link=>link.textContent===t.name));return{template:t.name,preview:preview.textContent};}})).catch(()=>{});}catch{}}
